### ISSUE TITLE
Installation fails, with "An Unknown Error Has Occurred"

### ISSUE THREAD

**Issue by MarjaE2** [t2linux/t2linux-fedora-iso#1]
I couldn't read the full error message, because it opened in a tiny window, which scrolls separarely from the rest of the screen.

I have disabled the system security utility. I had a failed Linux Mint partition, and tried to delete that to create space for Fedora. I can't see if that was deleted.

**Comment by MarjaE2** [comment]
This may be because I had not copied the wifi firmware. I cannot copy it with the included script.

**Comment by sharpenedblade** [comment]
> I couldn't read the full error message, because it opened in a tiny window, which scrolls separarely from the rest of the screen.

Without an error message it is hard to fix the problem, can you try again and look for any errors in `/tmp/anaconda.log`

> I have disabled the system security utility. I had a failed Linux Mint partition, and tried to delete that to create space for Fedora. I can't see if that was deleted.

The installer will only delete the partition after you click "continue" on the main installation screen.

> This may be because I had not copied the wifi firmware. I cannot copy it with the included script.

The installer works without wifi or bluetooth

**Comment by MarjaE2** [comment]
I can't get that far any more. I wiped the Mint partition from MacOS, replaced it with an exfat partition because I can't set free space or ext4 from there, and run into animation and error messages while trying to reclaim space.

I can't read the errors because I keep getting hit with animation, triggering my migraines, and because the text is too small.

**Comment by MarjaE2** [comment]
Okay, I managed to unmount the partition from the separate utility. I still get "an unknown error has occured," while "installing boot loader."

anaconda 38.23.4 exception report
Traceback (most recent call first):
File "/usr/lib/python3.11/site-packages//dasbus/client/handler.py" line 509 [cut off to the right]
raise exception from None
File "/usr/lib/python3.11/site-packages//dasbus/client/handler.py" line 483 [cut off to the right]
[cut off below]

Owing to migraines, I have a lot of trouble scrolling part of the page and not the whole thing.

**Comment by MarjaE2** [comment]
Owing to migraines, I can't edit out the extra slashes.

I have a Mac Mini 2018 (MacMini8,1). I am trying to install to a Samsung T7 ssd. I already have my main Mac partition on the Samsung T7 ssd. I am pretty sure I removed Samsung's software while prepping the drive.

**Comment by MarjaE2** [comment]
What I could see of the error matches this: https://discussion.fedoraproject.org/t/installer-crashes-when-attempting-to-install-on-a-dell-inspiron-3217u-from-around-2012/81301 but I am not sure what the solutioon means, or whether it applies on a Mac.

**Comment by MarjaE2** [comment]
This may be a duplicate of

https://bugzilla.redhat.com/show_bug.cgi?id=2210933

**Comment by MarjaE2** [comment]
I backuped up my data, wiped my hard drive, repartitioned it, tried again, and got the same error. I tried to copy and save the text in the error message, but the text editor went unresponsive.

**Comment by sharpenedblade** [comment]
> Owing to migraines, I can't edit out the extra slashes.

Extra slashes are ignored

Can you take a picture of the installer when you get to the partitioning step.

**Comment by MarjaE2** [comment]
I was trying again when I got your reply. This is the error message itself.

![Photo on 6-26-23 at 2 01 AM #2](https://github.com/t2linux/t2linux-fedora-iso/assets/12875862/7cfce74b-2255-4d34-ad9c-1ebaa206cf96)

**Comment by sharpenedblade** [comment]
Can you scroll (horizontally) to the end of the line

**Comment by MarjaE2** [comment]
After 509, it reads,

in _handle_method_error

After 483, it is

in _get_method_reply

If I paste into the text editor I get:
![Photo on 6-26-23 at 2 12 AM #2](https://github.com/t2linux/t2linux-fedora-iso/assets/12875862/658e8a15-c71c-4737-99bc-4d88b9eac0d3)

**Comment by sharpenedblade** [comment]
Reboot, try the install again, and when you get to "partitioning" post a screenshot.

**Comment by MarjaE2** [comment]
![Photo on 6-26-23 at 2 23 AM](https://github.com/t2linux/t2linux-fedora-iso/assets/12875862/cc15fcb7-9a88-4465-9979-54cf161d5807)

Also, checking the line numbers, the error messages in the 2nd screenshot are still a perfect match for the fedoraproject discussion linked above.

**Comment by sharpenedblade** [comment]
Scroll close to the bottom of error message, then take a screenshot. Then post the output of `sudo mount /dev/sda1 /mnt && ls -R /mnt` in the terminal

**Comment by MarjaE2** [comment]
![Photo on 6-26-23 at 2 54 AM](https://github.com/t2linux/t2linux-fedora-iso/assets/12875862/055c05bd-950b-47a4-9e92-818d3c2ac5fb)
![Photo on 6-26-23 at 2 55 AM](https://github.com/t2linux/t2linux-fedora-iso/assets/12875862/6ce2a508-6ce3-4590-9b56-f53005a95c0f)
![Photo on 6-26-23 at 2 56 AM](https://github.com/t2linux/t2linux-fedora-iso/assets/12875862/682cce1c-562b-4c51-993e-4b03472ef5ae)


ls: cannot open directory '/mnt': Permission denied

I did not get a password request, presumably because it's the live usb.

**Comment by sharpenedblade** [comment]
[Reset your nvram](https://support.apple.com/en-us/HT204063), then try to install again.

**Comment by MarjaE2** [comment]
Thanks! I finally have it installed. Now if only I can get everything working...

**Comment by sharpenedblade** [comment]
Is anything *not* working after running `firmware.sh` in the terminal app.

**Comment by MarjaE2** [comment]
I had to set up the firmware the other way.
