### ISSUE TITLE
Installer on Live USB does not respect Accessibility Settings

### ISSUE THREAD

**Issue by MarjaE2** [t2linux/t2linux-fedora-iso#2]
To test

1. Open Accessibility. Note that it can be hard to find.
2. Change settings such as text side, animation, scrollbars.
3. Start installer. If you increased text size, the installer has a lot of tiny text. If you disabled animation, the installer fires a lot of sliding animation after some of the errors.

This is probably inherited from standard Fedora 38.

**Comment by sharpenedblade** [comment]
> To test
> 
> 1. Open Accessibility. Note that it can be hard to find.
> 2. Change settings such as text side, animation, scrollbars.
> 3. Start installer. If you increased text size, the installer has a lot of tiny text. If you disabled animation, the installer fires a lot of sliding animation after some of the errors.
> 
> This is probably inherited from standard Fedora 38.

This is an upstream issue and I can not do anything about it. You should open a bug with upstream at https://bugzilla.redhat.com/enter_bug.cgi
